config/routes.rb
Wemadeyouacard::Application.routes.draw do
  resources :cards do 
    resources :messages
  end
  root :to => 'cards#index'

end

app/models/card.rb
class Card < ActiveRecord::Base
  attr_accessible :title
  has_many :messages
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :audio, :image
  belongs_to :card

  # mount_uploader :audio, AudioUploader
  mount_uploader :image, ImageUploader
  mount_uploader :audio, AudioUploader

  validates_presence_of :audio, :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cards }
    end
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
    @card = Card.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/new
  # GET /cards/new.json
  def new
    @card = Card.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/1/edit
  def edit
    @card = Card.find(params[:id])
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(params[:card])

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render json: @card, status: :created, location: @card }
      else
        format.html { render action: "new" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cards/1
  # PUT /cards/1.json
  def update
    @card = Card.find(params[:id])

    respond_to do |format|
      if @card.update_attributes(params[:card])
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card = Card.find(params[:id])
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  # GET /messages.json
  def index
    @messages = Card.find(params[:card_id]).messages

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @card = Card.find params[:card_id]
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(params[:message])

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to card_message_path(params[:card_id], @message.id), notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<div id='container'>
  Loading...
</div>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= form_for @card do |f| %>
  <%= f.label :title  %>
  <%= f.text_field :title  %>
  <%= f.submit %>
<% end %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>We made you a card</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "http://code.jquery.com/mobile/1.2.0/jquery.mobile.structure-1.2.0.min.css", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "http://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body class="ui-overlay-a">
  <%= yield %>
</body>
</html>

app/views/messages/_form.html.erb
<%= form_for( @message, :url => card_message_path(@message), :html => {:multipart => true}) do |f| %>
  <%= f.label :image %>
  <%= f.file_field :image, :accept => 'file', :accept => 'image/*;capture=camera' %>
  <br/>
  <%= f.label :audio %>
  <%= f.file_field :audio, :type => 'file', :accept => 'audio/*;capture=microphone' %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', card_message_path(params[:card_id], @message) %> |
<%= link_to 'Back', card_messages_path(params[:card_id])%>

app/views/messages/index.html.erb
<h1>Listing messages</h1>

<table>
  <tr>
    <th>mesage</th>
    <th>controls</th>
  </tr>

<% @messages.each do |message| %>
  <tr>
    <td><%= image_tag message.image_url %></td>
  </tr>
  <tr>
    <td><%= link_to 'Show', card_message_path(params[:card_id], message.id) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Message', new_card_message_path %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', card_messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @message.image_url %>
<audio controls id='audio_player' class="">
  <source src="<%=@message.audio_url%>" type="audio/ogg">
</audio>
<%= debug @message.inspect %>
<div id="cp_container" class="cp-container">
  <div class="cp-buffer-holder"> <!-- .cp-gt50 only needed when buffer is > than 50% -->
    <div class="cp-buffer-1"></div>
    <div class="cp-buffer-2"></div>
  </div>
  <div class="cp-progress-holder"> <!-- .cp-gt50 only needed when progress is > than 50% -->
    <div class="cp-progress-1"></div>
    <div class="cp-progress-2"></div>
  </div>
  <div class="cp-circle-control"></div>
  <ul class="cp-controls">
    <li><a class="cp-play" tabindex="1">play</a></li>
    <li><a class="cp-pause" style="display:none;" tabindex="1">pause</a></li> <!-- Needs the inline style here, or jQuery.show() uses display:inline instead of display:block -->
  </ul>
</div>
<%= link_to 'Edit', edit_card_message_path(@message) %> |
<%= link_to 'Back', card_messages_path %>